name: Pipeline DevSecOps

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Récupération du code
      uses: actions/checkout@v3

    - name: Configuration de PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Installation des dépendances
      run: composer install --no-interaction --no-scripts --prefer-dist

    - name: Vérification de la syntaxe PHP
      run: |
        find app routes -name "*.php" -exec php -l {} \;

    - name: Exécution des tests (optionnel)
      run: vendor/bin/phpunit --testdox || true

    - name: Construction de l’image Docker
      run: docker build -t akaunting-devsecops .

    - name: Analyse de sécurité (Trivy)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: akaunting-devsecops
        format: table
        exit-code: 0